In [1]:
import numpy as np

In [4]:
# 1. Create a NumPy array of numbers from 10 to 50
arr1 = np.arange(10, 51)
print("Array :", arr1)


Array : [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [6]:
# 2. Generate a 3×3 identity matrix
identity_matrix = np.eye(3,3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
# 3. Create a NumPy array of 10 random integers between 1 and 100
random_integers = np.random.randint(1, 101, size=10)
random_integers

array([71, 78, 23, 12, 87,  5, 70, 54,  9, 15])

In [9]:
# 4. Find the maximum and minimum of an array
max_value = np.max(random_integers)
min_value = np.min(random_integers)
print("Maximum value:", max_value)
print("Minimum value:", min_value)

Maximum value: 87
Minimum value: 5


In [11]:
# 5. Reshape a 1D array of 12 elements into a 3×4 matrix
random_integers = np.random.randint(1, 101, size=12)
reshaped_matrix = random_integers.reshape(3, 4)
reshaped_matrix

array([[22, 58, 42, 42],
       [79, 79, 33, 49],
       [13, 78, 30, 23]])

In [12]:
# 6. Create an array of all even numbers between 50 and 100
even_numbers = np.arange(50, 101, 2)
even_numbers

array([ 50,  52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,
        76,  78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [13]:
# 7. Compute the square of each element in [1,2,3,4,5]
array = np.array([1, 2, 3, 4, 5])
squared_array = np.square(array)
squared_array

array([ 1,  4,  9, 16, 25])

In [14]:
# 8. Create a 5×5 array of random numbers and find its mean
random_array = np.random.rand(5, 5)
mean_value = np.mean(random_array)
mean_value

np.float64(0.44040545471194287)

In [15]:
# 9. Find the index of the maximum element in [10, 20, 50, 40, 30]
array = np.array([10, 20, 50, 40, 30])
array.argmax()

np.int64(2)

In [16]:
# 10. Create two arrays and perform element-wise operation
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
sum_array = array1 + array2
product_array = array1 * array2
diff_array = array2 - array1
div_array = array2 / array1
mod_array = array2 % array1
sum_array, product_array, diff_array, div_array, mod_array


(array([5, 7, 9]),
 array([ 4, 10, 18]),
 array([3, 3, 3]),
 array([4. , 2.5, 2. ]),
 array([0, 1, 0]))