numpy 

In [1]:
import numpy as np

In [2]:
arr1 = np.ones(5)
print(arr1)

[1. 1. 1. 1. 1.]


In [3]:
arr2 = np.zeros(5)
print(arr2)

[0. 0. 0. 0. 0.]


In [6]:
arr3 = np.arange(1.5,10.5,2)
print(arr3)

[1.5 3.5 5.5 7.5 9.5]


In [9]:
arr4 = np.linspace(0,1,5)
print(arr4)

[0.   0.25 0.5  0.75 1.  ]
