Task: Perform array slicing

In [1]:
import numpy as np

In [2]:
arr = np.arange(1,15)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [3]:
print(arr[0:16])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [4]:
print(arr[0:])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [8]:
print(arr[9:-1])

[10 11 12 13]


In [9]:
print(arr[::])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [10]:
print(arr[:-1])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13]


In [11]:
print(arr[-1])

14


In [12]:
print(arr[::-1])

[14 13 12 11 10  9  8  7  6  5  4  3  2  1]


In [20]:
print(arr[12:])

[13 14]


# create an array with 6 elements between 1 and 10

In [26]:
arr1 = np.linspace(1,10,6)

In [27]:
print(arr1)

[ 1.   2.8  4.6  6.4  8.2 10. ]
