In [2]:
import numpy as np


In [3]:
arr1 = np.random.rand(5)
print(arr1)

[0.92782043 0.12314495 0.45909732 0.73447404 0.62171131]


In [4]:
#fancy indexing
print(arr1[[0,2,4]])

[0.92782043 0.45909732 0.62171131]


TASK: Extract the last 3 elements from the array

In [11]:
print(arr1[-3:])

[0.45909732 0.73447404 0.62171131]
