TASK: Extract the last 3 elements from the array

In [11]:
import numpy as np 

In [12]:
 arr = np.array([1,2,3,4,5,6,7,8,9,10])
 print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [13]:
print(arr[-3:])

[ 8  9 10]


Task 2:

In [14]:
arr = np.array([5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [15]:
#1.Slice and print every third element starting from index 1.
print(arr[1::3])


[10 25 40]


In [16]:
#2.Print the last 4 elements using negative indexing.
print(arr[-4:])

[35 40 45 50]


In [19]:
#3.Replace the values at even indices with -1.
arr1 = arr.copy()
arr1[::2]= -1
print(arr1)

[-1 10 -1 20 -1 30 -1 40 -1 50]


In [20]:
#4.Use fancy indexing to extract the values at positions [2, 4, 6, 8].
print(arr[[2,4,6,8]])

[15 25 35 45]
