In [1]:
import numpy as np

In [2]:
# create 3x3 array all filled with the value 9

arr = np.full(shape = (3,3), fill_value=9)
print(arr)

[[9 9 9]
 [9 9 9]
 [9 9 9]]


Task: Perform operations on 2d and 3d arrays

In [3]:
#basic operations on 2d arrays

#uisng arange to create an array and reshaping it to 2D
arr = np.arange(20)
print(f"\nOriginal Array: {arr}")
print(f"\nReshaped 2D array: \n{arr.reshape(4,5)}")


Original Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

Reshaped 2D array: 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [4]:
#using linspace to create an array and reshaping it to 2D
arr = np.linspace(0,19,20)
print(f"\nOriginal Array: {arr}")
print(f"\nReshaped Array: \n{arr.reshape(4,5)}")


Original Array: [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19.]

Reshaped Array: 
[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]]


In [5]:
#using random.rand / random.randn
arr = np.random.rand(3,3)
print(f"\nArray:\n {arr}")


Array:
 [[0.69358209 0.08199406 0.5136599 ]
 [0.18876375 0.47333441 0.94283996]
 [0.46264462 0.3455403  0.93670336]]


In [6]:
#arithmentic operations for 2d array
arr1 = np.random.randn(2,2)
arr2 = np.random.randn(2,2)

#addition
print(f"Addition: {arr1+arr2}")
#sub
print(f"Sub: {arr1-arr2}")
#mul
print(f"Mul: {arr1*arr2}")
#division
print(f"Divison: {arr1/arr2}")
#mod
print(f"MOd: {arr1%arr2}")
#power
print(f"Power: {arr1 ** 2}")



Addition: [[-1.40701137 -0.63584299]
 [-0.27744327 -1.30234287]]
Sub: [[0.37665296 0.50691361]
 [0.03407169 0.14259016]]
Mul: [[0.45945339 0.03683372]
 [0.01895347 0.41894125]]
Divison: [[0.57766385 0.11282313]
 [0.78125166 0.80263423]]
MOd: [[-0.5151792  -0.06446469]
 [-0.12168579 -0.57987636]]
Power: [[0.26540961 0.0041557 ]
 [0.01480743 0.33625659]]


In [7]:
arr = np.array([1, 2, 3])
arr + 5


array([6, 7, 8])

In [8]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([10, 20, 30])

A + b


array([[11, 22, 33],
       [14, 25, 36]])

Broadcasting can be only be done if 2 arrays have same dimension or on of the shape is 1

In [9]:
#masking and logical operator like == < > ! can be used similary
arr = np.array([
    [5, -2, 7],
    [0, 12, -4],
    [9, 3, -1]
])

mask = arr  > 2
print(mask)
print(arr[mask])

[[ True False  True]
 [False  True False]
 [ True  True False]]
[ 5  7 12  9  3]


In [10]:
# for 3d arrays now
#uisng arange to create an array and reshaping it to3D
arr = np.arange(40)
print(f"\nOriginal Array: {arr}")
print(f"\nReshaped 2D array: \n{arr.reshape(2,4,5)}")


Original Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]

Reshaped 2D array: 
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]]


In [11]:
#using linspace to create an array and reshaping it to 3D
arr = np.linspace(0,39,40)
print(f"\nOriginal Array: {arr}")
print(f"\nReshaped Array: \n{arr.reshape(2,4,5)}")


Original Array: [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39.]

Reshaped Array: 
[[[ 0.  1.  2.  3.  4.]
  [ 5.  6.  7.  8.  9.]
  [10. 11. 12. 13. 14.]
  [15. 16. 17. 18. 19.]]

 [[20. 21. 22. 23. 24.]
  [25. 26. 27. 28. 29.]
  [30. 31. 32. 33. 34.]
  [35. 36. 37. 38. 39.]]]


In [12]:
#using random.rand / random.randn
arr = np.random.rand(2,3,3)
print(f"\nArray:\n {arr}")


Array:
 [[[0.75179537 0.12568631 0.33066313]
  [0.07852733 0.42999669 0.06826161]
  [0.04316391 0.57522955 0.12045389]]

 [[0.36923087 0.33839646 0.2264293 ]
  [0.68288591 0.76326942 0.73116352]
  [0.92084985 0.54803252 0.4416401 ]]]


In [13]:
#arithmentic operations for 3d array
arr1 = np.random.randn(2,2,2)
arr2 = np.random.randn(2,2,2)

#addition
print(f"Addition: {arr1+arr2}")
#sub
print(f"Sub: {arr1-arr2}")
#mul
print(f"Mul: {arr1*arr2}")
#division
print(f"Divison: {arr1/arr2}")
#mod
print(f"MOd: {arr1%arr2}")
#power
print(f"Power: {arr1 ** 2}")


Addition: [[[ 0.02963725 -0.55946647]
  [ 1.45295889  2.03412936]]

 [[-0.59251252 -1.04403978]
  [ 1.52330024 -0.09018201]]]
Sub: [[[ 1.44505738 -0.03172509]
  [-0.14574837 -1.68387779]]

 [[ 0.19498305 -2.08887626]
  [ 1.58719965 -0.30819472]]]
Mul: [[[-0.52182812  0.07799906]
  [ 0.52246173  0.32555946]]

 [[ 0.07826317 -0.81834624]
  [-0.04968978 -0.0217128 ]]]
Divison: [[[ -1.04187767   1.12022969]
  [  0.81766722   0.09420411]]

 [[  0.50480216  -2.998475  ]
  [-48.67806782  -1.82730963]]]
MOd: [[[-0.67807282 -0.03172509]
  [ 0.65360526  0.17512579]]

 [[-0.19876473  0.00079669]
  [-0.01028564  0.01882435]]]
Power: [[[0.54368106 0.08737687]
  [0.42719983 0.03066904]]

 [[0.03950742 2.45379073]
  [2.41880239 0.039676  ]]]


In [14]:
arr = np.arange(24).reshape(2, 3, 4)
print("array:\n", arr)

array:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [15]:
b = np.array([100, 200, 300, 400])  
result = arr + b
print("broadcasting:\n", result)

broadcasting:
 [[[100 201 302 403]
  [104 205 306 407]
  [108 209 310 411]]

 [[112 213 314 415]
  [116 217 318 419]
  [120 221 322 423]]]


In [16]:
mask = arr > 10
print("Mask:\n", mask)
print("Rsult:\n", arr[mask])


Mask:
 [[[False False False False]
  [False False False False]
  [False False False  True]]

 [[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]]
Rsult:
 [11 12 13 14 15 16 17 18 19 20 21 22 23]


In [17]:
mask = (arr % 2 == 0) & (arr > 5)
print("Masked for even & >5:\n", mask)
print("Result:\n", arr[mask])

#similary or not ani <> != use garna milcha

Masked for even & >5:
 [[[False False False False]
  [False False  True False]
  [ True False  True False]]

 [[ True False  True False]
  [ True False  True False]
  [ True False  True False]]]
Result:
 [ 6  8 10 12 14 16 18 20 22]


In [18]:
print(arr)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
