In [1]:
import numpy as np

In [4]:
# create 3x3 array all filled with the value 9

arr = np.full(shape = (3,3), fill_value=9)
print(arr)

[[9 9 9]
 [9 9 9]
 [9 9 9]]


Task: Perform operations on 2d and 3d arrays

In [ ]:
#basic operations on 2d arrays

#uisng arange to create an array and reshaping it to 2D
arr = np.arange(20)
print(f"\nOriginal Array: {arr}")
print(f"\nReshaped 2D array: \n{arr.reshape(4,5)}")


Original Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

Reshaped 2D array: 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [21]:
#using linspace to create an array and reshaping it to 2D
arr = np.linspace(0,19,20)
print(f"\nOriginal Array: {arr}")
print(f"\nReshaped Array: \n{arr.reshape(4,5)}")


Original Array: [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19.]

Reshaped Array: 
[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]]


In [23]:
#using random.rand / random.randn
arr = np.random.rand(3,3)
print(f"\nArray:\n {arr}")


Array:
 [[0.36448142 0.58976125 0.74218427]
 [0.44640579 0.56240436 0.75216377]
 [0.93798541 0.60116158 0.33330517]]


In [25]:
#arithmentic operations for 2d array
arr1 = np.random.randn(2,2)
arr2 = np.random.randn(2,2)

#addition
print(f"Addition: {arr1+arr2}")
#sub
print(f"Sub: {arr1-arr2}")
#mul
print(f"Mul: {arr1*arr2}")
#division
print(f"Divison: {arr1/arr2}")
#mod
print(f"MOd: {arr1%arr2}")
#power
print(f"Power: {arr1 ** 2}")



Addition: [[ 1.48108429  2.54309821]
 [-0.94889448 -0.29018364]]
Sub: [[ 2.25159958  0.98629631]
 [-0.22643173 -0.26547978]]
Mul: [[-0.71902249  1.37364202]
 [ 0.21228235  0.00343176]]
Divison: [[-4.84439951  2.26708004]
 [ 1.62683297 22.4929853 ]]
MOd: [[-0.05994628  0.20789536]
 [-0.22643173 -0.00608932]]
Power: [[3.48323222 3.11415642]
 [0.34534793 0.07719046]]


In [26]:
arr = np.array([1, 2, 3])
arr + 5


array([6, 7, 8])

In [27]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([10, 20, 30])

A + b


array([[11, 22, 33],
       [14, 25, 36]])

Broadcasting can be only be done if 2 arrays have same dimension or on of the shape is 1

In [35]:
#masking and logical operator like == < > ! can be used similary
arr = np.array([
    [5, -2, 7],
    [0, 12, -4],
    [9, 3, -1]
])

mask = arr  > 2
print(mask)
print(arr[mask])

[[ True False  True]
 [False  True False]
 [ True  True False]]
[ 5  7 12  9  3]


In [38]:
# for 3d arrays now
#uisng arange to create an array and reshaping it to3D
arr = np.arange(40)
print(f"\nOriginal Array: {arr}")
print(f"\nReshaped 2D array: \n{arr.reshape(2,4,5)}")


Original Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]

Reshaped 2D array: 
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]]


In [43]:
#using linspace to create an array and reshaping it to 3D
arr = np.linspace(0,39,40)
print(f"\nOriginal Array: {arr}")
print(f"\nReshaped Array: \n{arr.reshape(2,4,5)}")


Original Array: [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39.]

Reshaped Array: 
[[[ 0.  1.  2.  3.  4.]
  [ 5.  6.  7.  8.  9.]
  [10. 11. 12. 13. 14.]
  [15. 16. 17. 18. 19.]]

 [[20. 21. 22. 23. 24.]
  [25. 26. 27. 28. 29.]
  [30. 31. 32. 33. 34.]
  [35. 36. 37. 38. 39.]]]


In [44]:
#using random.rand / random.randn
arr = np.random.rand(2,3,3)
print(f"\nArray:\n {arr}")


Array:
 [[[0.58062641 0.41250368 0.1394758 ]
  [0.42935964 0.64818896 0.3399246 ]
  [0.07895217 0.88998429 0.2068855 ]]

 [[0.19293416 0.72156718 0.85078286]
  [0.77941335 0.61983308 0.43120385]
  [0.59251078 0.37091703 0.86888727]]]


In [45]:
#arithmentic operations for 3d array
arr1 = np.random.randn(2,2,2)
arr2 = np.random.randn(2,2,2)

#addition
print(f"Addition: {arr1+arr2}")
#sub
print(f"Sub: {arr1-arr2}")
#mul
print(f"Mul: {arr1*arr2}")
#division
print(f"Divison: {arr1/arr2}")
#mod
print(f"MOd: {arr1%arr2}")
#power
print(f"Power: {arr1 ** 2}")


Addition: [[[ 1.91330016  2.04227118]
  [-0.0197642   0.59977279]]

 [[-1.87693596  2.7197157 ]
  [ 0.16135427  0.78249742]]]
Sub: [[[ 0.21061787  1.01259872]
  [-0.47876195 -1.34592032]]

 [[-3.22086162 -0.88195933]
  [-2.24543498  1.43481206]]]
Mul: [[[ 0.90408941  0.78637886]
  [-0.05720559 -0.36294353]]

 [[-1.71276525  1.65475031]
  [-1.25398577 -0.36159586]]]
Divison: [[[ 1.24739538  2.96683654]
  [-1.08611895 -0.38348675]]

 [[-3.79321396  0.51025047]
  [-0.86591741 -3.39914103]]]
MOd: [[[ 0.21061787  0.49776248]
  [ 0.20973467  0.59977279]]

 [[ 0.13895253  0.91887819]
  [ 0.16135427 -0.19597455]]]
Power: [[[1.12775695 2.33305753]
  [0.06213208 0.13918403]]

 [[6.49688505 0.84433712]
  [1.0858481  1.22911533]]]


In [46]:
arr = np.arange(24).reshape(2, 3, 4)
print("array:\n", arr)

array:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [47]:
b = np.array([100, 200, 300, 400])  
result = arr + b
print("broadcasting:\n", result)

broadcasting:
 [[[100 201 302 403]
  [104 205 306 407]
  [108 209 310 411]]

 [[112 213 314 415]
  [116 217 318 419]
  [120 221 322 423]]]


In [48]:
mask = arr > 10
print("Mask:\n", mask)
print("Rsult:\n", arr[mask])


Mask:
 [[[False False False False]
  [False False False False]
  [False False False  True]]

 [[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]]
Rsult:
 [11 12 13 14 15 16 17 18 19 20 21 22 23]


In [51]:
mask = (arr % 2 == 0) & (arr > 5)
print("Masked for even & >5:\n", mask)
print("Result:\n", arr[mask])

#similary or not ani <> != use garna milcha

Masked for even & >5:
 [[[False False False False]
  [False False  True False]
  [ True False  True False]]

 [[ True False  True False]
  [ True False  True False]
  [ True False  True False]]]
Result:
 [ 6  8 10 12 14 16 18 20 22]
