In [2]:
import numpy as np

In [4]:
#1. Create a 3x3 matrix with values from 1 to 9(2d array):

arr = np.arange(1,10).reshape(3,3)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
#2. Create an array of 10 random floats between 0 and 1, and round to 2 decimal places.

arr = np.random.rand(10).round(2)
print(arr)

[0.82 0.4  0.44 0.49 0.28 0.09 0.7  0.19 0.01 0.22]


In [9]:
#3.Find all even numbers in the array [1, 3, 6, 9, 12, 15] using Boolean indexing

arr = np.array([1, 3, 6, 9, 12, 15])
mask = arr % 2 == 0
print(arr[mask])

[ 6 12]


In [10]:
#4.Create a 4x4 matrix filled with 7
arr = np.full((4,4), fill_value=7)
print(arr)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


Create a 3D array of shape (3, 4, 5) filled with random integers between 1 and 100.
Perform the following tasks:

In [18]:
arr = np.random.randint(1,100, size=(3,4,5))
print(arr)

[[[24 77 96 60 34]
  [85 79 51 28  5]
  [ 9 60 33 88 74]
  [20  7 76 52  8]]

 [[ 1 64 52 16 89]
  [29 24 78 31 62]
  [22 62 23 76 93]
  [60 30 89  4 58]]

 [[72 75 93 90 48]
  [47 90  2 43 27]
  [58 99 51  6 12]
  [70 79 37 50 96]]]


In [19]:
#Replace all elements greater than the mean of the entire array with 0.

mean = arr.mean()
arr[arr > mean] = 0
print(mean)
print(arr)

51.233333333333334
[[[24  0  0  0 34]
  [ 0  0 51 28  5]
  [ 9  0 33  0  0]
  [20  7  0  0  8]]

 [[ 1  0  0 16  0]
  [29 24  0 31  0]
  [22  0 23  0  0]
  [ 0 30  0  4  0]]

 [[ 0  0  0  0 48]
  [47  0  2 43 27]
  [ 0  0 51  6 12]
  [ 0  0 37 50  0]]]


In [20]:
#Calculate the sum along axis=1 (i.e., sum across the 5 columns in each depth slice).
sum = arr.sum(axis =1)
print(sum)

[[53  7 84 28 47]
 [52 54 23 51  0]
 [47  0 90 99 87]]


In [22]:
#Extract a new 2D array that contains only the first and last columns from each row of each depth slice.
arr2D = arr[:,:,[0,-1]]
print(arr2D)

[[[24 34]
  [ 0  5]
  [ 9  0]
  [20  8]]

 [[ 1  0]
  [29  0]
  [22  0]
  [ 0  0]]

 [[ 0 48]
  [47 27]
  [ 0 12]
  [ 0  0]]]
